# Site settings
title: Anemoi - New College of Florida's Journal of Pre-Modern Studies
email: anemoijournal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  New College of Florida's Journal of Pre-Modern Studies
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Anemoi_Journal
github_username:  AnemoiJournal
tumblr username: AnemoiAcademicJournal

# Build settings
markdown: kramdown
permalink: /:title
